### PR TITLE
Update MaxMind DB to 2019-08-28 version

### PR DESCRIPTION
**Pull request by scalder27**
MaxMind database out of date a bit.

For example, in current 1.3.7 version, `92.119.177.198` resolves as Romania, but actually its USA IP. Updated MaxMind database handles it.

### CODE REVIEW

**Comment by bluesmoon** [comment]
Cannot see the details, but github tells me that the geo-city dat files have had significant reductions in size. Is this intentional?  Also, I don't think the package.json changes are related and maybe package-lock.json shouldn't be in this PR.

**Comment by ar2rsawseen** [comment]
Also, I guess tests should be updated, since data change

**Comment by scalder27** [comment]
@bluesmoon, hi. I've just run `updatedb` script. I thought that's the way to sync database data with  MaxMind.

**Comment by scalder27** [comment]
@ar2rsawseen, I've updated tests. But one of them bothering me:

```typescript
	testIPv4MappedIPv6: function (test) {
		test.expect(2);

		var actual = geoip.lookup("::ffff:173.185.182.82");

		test.equal(actual.city, "Baird");
		test.equal(actual.metro, 662);

		test.done();
	},
```

After update, `173.185.182.82` IP resolves with `Baird` city, but everywhere I've checked it's still `Granbury`. Including [MaxMind site](https://www.maxmind.com/en/geoip2-precision-demo). So now I'm not so sure about the city's database update.

**Comment by bluesmoon** [comment]
Maxmind website uses the commercial database, while updatedb updates to the free version which is less correct. That would explain some level of difference.

**Comment by scalder27** [comment]
@bluesmoon, it might. About reduction in size - do you want me to return the city's databases back?

**Comment by bluesmoon** [comment]
No, just verify that it's the right thing.

**Comment by scalder27** [comment]
@bluesmoon is there is some common/legit/efffective way to verify it?

**Comment by bluesmoon** [comment]
probably simplest would be to compare the sizes of the MaxMind csv files and see if it has a matching change in file size.

**Comment by scalder27** [comment]
@bluesmoon,

The difference b/w current version (GeoLite2-City-CSV_20190820) and version from June 2019 (GeoLite2-City-CSV_20190611):
```
GeoLite2-City-Locations-en.csv  9.8     ->  10.1    103%
GeoLite2-City-Blocks-IPv4.csv   197.3   ->  182.9   92.7%
GeoLite2-City-Blocks-IPv6.csv   27.9    ->  24.9    89.25%
```

I'd say it means that the reduction in size for cities is pretty reasonable.

**Comment by scalder27** [comment]
@bluesmoon,

could we proceed?

**Comment by scalder27** [comment]
@bluesmoon, sorry to bother you, but - any news/comments?

**Comment by bluesmoon** [comment]
Was away on vacation, will take a look at it.

**Comment by scalder27** [comment]
@bluesmoon, sure no problem! If I knew I'd be more patient =)

**Comment by scalder27** [comment]
@bluesmoon, I've updated DB again - no reduction in the size now.

**Comment by scalder27** [comment]
Squashed all commits to a single one, and dropped out coincidental changes aka NPM's lock file and formatted package.json.

**Comment by scalder27** [comment]
@bluesmoon, hi!
Did you have a chance to check it?

**Comment by scalder27** [comment]
@bluesmoon, thank you for verifying the PR!

**Pull request merged**
