### PR TITLE
update iconv-lite

### PR DESCRIPTION
**Pull request by ecwyne**

### CODE REVIEW

**Comment by ecwyne** [comment]
Any movement on this @bluesmoon?

**Comment by bluesmoon** [comment]
I like the change. Will merge on Monday as I'm afk on the weekend and I
can't merge from the github app on my phone.

**Comment by ecwyne** [comment]
Thank you for the merge! Any idea when a new NPM version will be published?

**Comment by bluesmoon** [comment]
pushed

**Comment by ecwyne** [comment]
Awesome, Thanks!!

**Pull request merged**
