### PR TITLE
Update download URL

### PR DESCRIPTION
**Pull request by ar2rsawseen**
Tested, new URL works

### CODE REVIEW

**Comment by ar2rsawseen** [comment]
Travis fails because License key is not exposed to PR from outside repos
Not sure what other options we would have there, except removing building the data

**Comment by kmcnerney-salesforce** [comment]
This change shouldn't affect the license key, right? How was the script succeeding before without license key?

**Comment by ar2rsawseen** [comment]
It never succeeded on the outside repo PR, because travis does not disclose sensitive information like license key to outside repo PR (because it can be used, tracked, send somewhere, etc)
it only succeeds after merging

**Comment by kmcnerney-salesforce** [comment]
Hey @ar2rsawseen, do you know how we can take the next step to get this released? Maybe just remove the data update from travis unless it's the master branch?

**Pull request merged**
