### PR TITLE
Updated data files from geoip2

### PR DESCRIPTION
**Pull request by ar2rsawseen**

### CODE REVIEW

**Comment by bluesmoon** [comment]
can you provide a more detailed description since I see there were many commits.

**Comment by bluesmoon** [comment]
nvm, I see the discussion on #137

**Comment by ar2rsawseen** [comment]
Strange, these are the same commits from previous PR, I thought they should have been merged, but rechecking commit history I don't see them in this repo, although code modifications seem to be there.

**Comment by bluesmoon** [comment]
I would have done a squash merge to combine everything into a single commit.

**Comment by ar2rsawseen** [comment]
ok, I see, so if you want me to update the PR to include only related commits let me know, or you can squash merge it again?

**Comment by Gourmentt** [comment]
@ar2rsawseen any news on it?

**Comment by ar2rsawseen** [comment]
It is up to @bluesmoon now :)

**Comment by bluesmoon** [comment]
hope it works now.

**Comment by Gourmentt** [comment]
@bluesmoon @ar2rsawseen thank you guys, it works now :+1:

**Pull request merged**
